import { NextRequest, NextResponse } from "next/server";
import { defaultLocale, isLocale } from "@/i18n/config";

const PUBLIC_FILE = /\.[^/]+$/;

// Root-level metadata routes generated by the App Router (no file extension,
// so they must be excluded from locale redirection explicitly).
const METADATA_ROUTES = new Set([
  "/icon",
  "/apple-icon",
  "/opengraph-image",
  "/manifest.webmanifest",
  "/sitemap.xml",
  "/robots.txt",
]);

/**
 * Locale routing:
 *  - `/` → best-match locale (Accept-Language, else default)
 *  - `/xx/...` where xx is a supported locale → pass through
 *  - anything else with no locale prefix → prefix with best-match locale
 */
function pickLocale(req: NextRequest): string {
  const header = req.headers.get("accept-language");
  if (header) {
    const requested = header
      .split(",")
      .map((part) => part.split(";")[0]?.trim().slice(0, 2).toLowerCase())
      .filter(Boolean) as string[];
    for (const code of requested) {
      if (isLocale(code)) return code;
    }
  }
  return defaultLocale;
}

export function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;

  // Skip Next internals, API and static assets.
  if (
    pathname.startsWith("/_next") ||
    pathname.startsWith("/api") ||
    METADATA_ROUTES.has(pathname) ||
    PUBLIC_FILE.test(pathname)
  ) {
    return NextResponse.next();
  }

  const segments = pathname.split("/");
  const first = segments[1] ?? "";

  if (isLocale(first)) {
    return NextResponse.next();
  }

  const locale = pickLocale(req);
  const url = req.nextUrl.clone();
  url.pathname = `/${locale}${pathname === "/" ? "" : pathname}`;
  return NextResponse.redirect(url);
}

export const config = {
  matcher: [
    // Everything except Next internals, api, metadata routes, and files
    // with an extension.
    "/((?!_next|api|icon|apple-icon|opengraph-image|.*\\..*).*)",
  ],
};
